apiVersion: v1
kind: Service
metadata:
  name: terraform-viewer
  namespace: tfplan-system
  labels:
    app: terraform-viewer
spec:
  type: NodePort
  selector:
    app: terraform-viewer
  ports:
    - port: 8000
      targetPort: 8000
      nodePort: 30082
      protocol: TCP
